// AUTO-GENERATED by scripts/rebake-v4-static-templates.ts at 2026-05-09T10:14:45.734Z
// Source: action=manualEntry client=腾讯
// Fully baked — only {{RUNTIME_INPUT}} placeholder remains.
// DO NOT EDIT — regenerate after v4 skeleton/template changes.

import type { ActionObjectV4 } from "../../types";

export const template: ActionObjectV4 = {
  "prompt": "## Human-actor action (no agent execution)\n\nAction `manualEntry` is performed by a human operator (Human). The agent does NOT execute this action. If you receive a request to evaluate this action:\n- Acknowledge that the action requires human handover\n- Surface the relevant context and rules (if any) so the human knows what to do\n- Return a stub output with `{ \"status\": \"human_handover_required\", \"actor\": \"Human\" }`\n\n## Action context\n\n- Category: 人工操作\n- Trigger: (none)\n\nDescription:\n人工需求录入 - 交付经理或招聘专员在RAAS系统中手动创建和录入客户招聘需求信息，包括岗位名称、职级要求、招聘人数、工作城市等核心字段。录入完成后触发需求分析流程。\n\n## Inputs\n\nIf the runtime supplies input data for this action (for context only, not for agent execution):\n\n{{RUNTIME_INPUT}}\n\n## Output\n\nReturn a JSON stub:\n```json\n{\n  \"status\": \"human_handover_required\",\n  \"actor\": [\n    \"Human\"\n  ],\n  \"context\": \"see Inputs above\"\n}\n```",
  "meta": {
    "actionId": "1-2",
    "actionName": "manualEntry",
    "domain": "RAAS-v1",
    "client": "腾讯",
    "compiledAt": "2026-05-09T10:14:45.734Z",
    "templateVersion": "v4",
    "promptStrategy": "v4-3",
    "validation": {
      "driftDetected": false,
      "roundTripFailures": [],
      "missingInstructions": []
    }
  }
};

export default template;
