// AUTO-GENERATED by scripts/rebake-v4-static-templates.ts at 2026-05-09T10:14:46.070Z
// Source: action=packageSupplement client=字节
// Fully baked — only {{RUNTIME_INPUT}} placeholder remains.
// DO NOT EDIT — regenerate after v4 skeleton/template changes.

import type { ActionObjectV4 } from "../../types";

export const template: ActionObjectV4 = {
  "prompt": "## Human-actor action (no agent execution)\n\nAction `packageSupplement` is performed by a human operator (Human). The agent does NOT execute this action. If you receive a request to evaluate this action:\n- Acknowledge that the action requires human handover\n- Surface the relevant context and rules (if any) so the human knows what to do\n- Return a stub output with `{ \"status\": \"human_handover_required\", \"actor\": \"Human\" }`\n\n## Action context\n\n- Category: 人工操作\n- Trigger: PACKAGE_MISSING_INFO\n\nDescription:\n推荐包信息补全 - 招聘专员补全推荐包缺失的必填信息\n\n## Inputs\n\nIf the runtime supplies input data for this action (for context only, not for agent execution):\n\n{{RUNTIME_INPUT}}\n\n## Output\n\nReturn a JSON stub:\n```json\n{\n  \"status\": \"human_handover_required\",\n  \"actor\": [\n    \"Human\"\n  ],\n  \"context\": \"see Inputs above\"\n}\n```",
  "meta": {
    "actionId": "14-2",
    "actionName": "packageSupplement",
    "domain": "RAAS-v1",
    "client": "字节",
    "compiledAt": "2026-05-09T10:14:46.070Z",
    "templateVersion": "v4",
    "promptStrategy": "v4-3",
    "validation": {
      "driftDetected": false,
      "roundTripFailures": [],
      "missingInstructions": []
    }
  }
};

export default template;
