// AUTO-GENERATED by scripts/rebake-v4-static-templates.ts at 2026-05-09T10:14:46.173Z
// Source: action=requirementReClarification client=腾讯
// Fully baked — only {{RUNTIME_INPUT}} placeholder remains.
// DO NOT EDIT — regenerate after v4 skeleton/template changes.

import type { ActionObjectV4 } from "../../types";

export const template: ActionObjectV4 = {
  "prompt": "## Human-actor action (no agent execution)\n\nAction `requirementReClarification` is performed by a human operator (Human). The agent does NOT execute this action. If you receive a request to evaluate this action:\n- Acknowledge that the action requires human handover\n- Surface the relevant context and rules (if any) so the human knows what to do\n- Return a stub output with `{ \"status\": \"human_handover_required\", \"actor\": \"Human\" }`\n\n## Action context\n\n- Category: 人工操作\n- Trigger: CLARIFICATION_INCOMPLETE\n\nDescription:\n需求重新澄清 - HSM根据需求分析Agent输出的待澄清问题清单，与客户进行沟通确认，将澄清结果录入系统。完成后触发CLARIFICATION_RETRY事件驱动需求分析Agent重新校验。\n\n## Inputs\n\nIf the runtime supplies input data for this action (for context only, not for agent execution):\n\n{{RUNTIME_INPUT}}\n\n## Output\n\nReturn a JSON stub:\n```json\n{\n  \"status\": \"human_handover_required\",\n  \"actor\": [\n    \"Human\"\n  ],\n  \"context\": \"see Inputs above\"\n}\n```",
  "meta": {
    "actionId": "3-2",
    "actionName": "requirementReClarification",
    "domain": "RAAS-v1",
    "client": "腾讯",
    "compiledAt": "2026-05-09T10:14:46.173Z",
    "templateVersion": "v4",
    "promptStrategy": "v4-3",
    "validation": {
      "driftDetected": false,
      "roundTripFailures": [],
      "missingInstructions": []
    }
  }
};

export default template;
