/**
 * Emit stage — `ActionObject` → TS source string.
 *
 * Spec §8.2 / §8.3 / §8.5: hand-rolled string concatenation, three-line banner,
 * top-level keys in declaration order, `prompt` as backtick template literal
 * with three escape rules, every other field via `stableJson(value, 2)`.
 */

import { stableJson } from "./compile/stable-json";
import type { EmitOptions } from "./types.internal";
import type { ActionObject } from "./types.public";

export function emitActionObjectModule(obj: ActionObject, opts: EmitOptions): string {
  const exportName = `${obj.name}ActionObject`;
  const banner = renderBanner(obj);

  const lines: string[] = [];
  lines.push(banner);
  lines.push("");
  lines.push(`import type { ActionObject } from "${opts.typesImportPath}";`);
  lines.push("");
  lines.push(`export const ${exportName}: ActionObject = {`);

  // Top-level fields in declaration order (mirror block, then compilation, then provenance).
  // Mirror block:
  lines.push(`  id: ${stableJson(obj.id, 2)},`);
  lines.push(`  name: ${stableJson(obj.name, 2)},`);
  lines.push(`  description: ${stableJson(obj.description, 2)},`);
  lines.push(`  submissionCriteria: ${stableJson(obj.submissionCriteria, 2)},`);
  lines.push(`  category: ${stableJson(obj.category, 2)},`);
  lines.push(`  actor: ${indent(stableJson(obj.actor, 2), 2)},`);
  lines.push(`  trigger: ${indent(stableJson(obj.trigger, 2), 2)},`);
  lines.push(`  targetObjects: ${indent(stableJson(obj.targetObjects, 2), 2)},`);
  lines.push(`  inputs: ${indent(stableJson(obj.inputs, 2), 2)},`);
  lines.push(`  outputs: ${indent(stableJson(obj.outputs, 2), 2)},`);
  lines.push(`  actionSteps: ${indent(stableJson(obj.actionSteps, 2), 2)},`);
  lines.push(`  sideEffects: ${indent(stableJson(obj.sideEffects, 2), 2)},`);
  lines.push(`  triggeredEvents: ${indent(stableJson(obj.triggeredEvents, 2), 2)},`);
  lines.push("");

  // Compilation block:
  lines.push(`  prompt: \`${escapePromptForBacktick(obj.prompt)}\`,`);
  lines.push("");
  lines.push(`  sections: ${indent(stableJson(obj.sections, 2), 2)},`);
  lines.push("");

  // Provenance block:
  lines.push(`  meta: ${indent(stableJson(obj.meta, 2), 2)},`);

  lines.push(`};`);
  lines.push("");

  return lines.join("\n");
}

/**
 * Escape a string for embedding inside a backtick-delimited template literal.
 * Spec §8.3 — three rules in this exact order:
 *   1. `\` → `\\`
 *   2. `` ` `` → `` \` ``
 *   3. `${` → `\${`
 */
export function escapePromptForBacktick(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

/**
 * Indent every line of `s` after the first by `cols` spaces. The first line is
 * already positioned at the right column by its caller. This keeps a multi-line
 * `stableJson` output (with internal `\n  `) readable inside the emitted file.
 */
function indent(s: string, cols: number): string {
  const pad = " ".repeat(cols);
  return s.replace(/\n/g, `\n${pad}`);
}

function renderBanner(obj: ActionObject): string {
  return [
    `// AUTO-GENERATED by scripts/gen-action-snapshot.ts at ${obj.meta.compiledAt}`,
    `// source: action=${obj.meta.actionName} id=${obj.meta.actionId} domain=${obj.meta.domain} template=${obj.meta.templateVersion}`,
    `// DO NOT EDIT — regenerate via: npm run gen:ontology -- --action-name ${obj.meta.actionName}`,
  ].join("\n");
}
