// AUTO-GENERATED by scripts/gen-v4-human-templates.ts at 2026-05-09T08:35:27.365Z
// Source: action=manualPublish (Human actor)
// DO NOT EDIT — regenerate via: node --env-file=.env.local --import tsx scripts/gen-v4-human-templates.ts

import type { ActionObjectV4, EnrichedAction } from "../../types";
import { renderHumanTaskActionObject } from "../human-task-helper";

export function manualPublishTemplate(
  enriched: EnrichedAction,
  options: { client?: string; runtimeInput?: string | Record<string, unknown> },
): ActionObjectV4 {
  return renderHumanTaskActionObject(enriched, options);
}

export default manualPublishTemplate;
