#!/usr/bin/env node
/**
 * Generate v4 templates for Human-actor actions (no LLM needed).
 *
 * Each Human action gets a per-action template file (V4-2) plus a per-(action,client)
 * static literal (V4-3) for each known client.
 *
 * Run after fetching upstream Action data — these templates encode the action's
 * description / inputs / outputs from the API but do not transform any rules
 * (rules are passed through to humans, not executed by the agent).
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { fetchAction } from "../lib/ontology-gen/fetch";

const HUMAN_ACTIONS = [
  "manualPublish",
  "manualEntry",
  "packageSupplement",
  "jdReview",
  "resumeCollection",
  "interviewExecution",
  "resumeFix",
  // The 2 Human actions WITH rules — we still emit a Human handover template for now;
  // when LLM transform pipeline is run for them, swap to full v4 templates.
  "requirementReClarification",
  "packageReview",
];

const CLIENTS = ["通用", "腾讯", "字节"] as const;

main().catch((err) => {
  process.stderr.write(`gen-v4-human-templates failed: ${err instanceof Error ? err.stack ?? err.message : String(err)}\n`);
  process.exit(1);
});

async function main(): Promise<void> {
  const here = dirname(fileURLToPath(import.meta.url));
  const v4Dir = resolve(here, "../lib/ontology-gen/v4/templates");

  for (const actionName of HUMAN_ACTIONS) {
    process.stderr.write(`[gen:v4-human] ${actionName}\n`);
    let action;
    try {
      action = await fetchAction({ actionRef: actionName, domain: "RAAS-v1", apiToken: process.env["ONTOLOGY_API_TOKEN"] ?? "" });
    } catch (err) {
      process.stderr.write(`  ✘ fetch failed: ${err instanceof Error ? err.message : String(err)}\n`);
      continue;
    }

    const kebab = toKebab(actionName);
    const camel = toCamelLower(actionName);

    // V4-2: function template that delegates to renderHumanTaskActionObject
    const v4_2_path = resolve(v4Dir, "v4-2", `${kebab}.template.ts`);
    const v4_2_content = `// AUTO-GENERATED by scripts/gen-v4-human-templates.ts at ${new Date().toISOString()}
// Source: action=${actionName} (Human actor)
// DO NOT EDIT — regenerate via: node --env-file=.env.local --import tsx scripts/gen-v4-human-templates.ts

import type { ActionObjectV4, EnrichedAction } from "../../types";
import { renderHumanTaskActionObject } from "../human-task-helper";

export function ${camel}Template(
  enriched: EnrichedAction,
  options: { client?: string; runtimeInput?: string | Record<string, unknown> },
): ActionObjectV4 {
  return renderHumanTaskActionObject(enriched, options);
}

export default ${camel}Template;
`;
    await mkdir(dirname(v4_2_path), { recursive: true });
    await writeFile(v4_2_path, v4_2_content, "utf8");
    process.stderr.write(`  ✓ wrote ${v4_2_path}\n`);

    // V4-3: per-client static literal (Human actions are client-agnostic in content,
    // so all 3 clients produce essentially identical prompts — but we generate all 3
    // to maintain parallel structure across V4-3 templates).
    for (const client of CLIENTS) {
      const v4_3_path = resolve(v4Dir, "v4-3", `${kebab}.${client}.template.ts`);
      const obj = await renderHuman(action, client);
      const v4_3_content = `// AUTO-GENERATED by scripts/gen-v4-human-templates.ts at ${new Date().toISOString()}
// Source: action=${actionName} client=${client} (Human actor)

import type { ActionObjectV4 } from "../../types";

export const template: ActionObjectV4 = ${JSON.stringify(obj, null, 2)};

export default template;
`;
      await mkdir(dirname(v4_3_path), { recursive: true });
      await writeFile(v4_3_path, v4_3_content, "utf8");
      process.stderr.write(`  ✓ wrote ${v4_3_path}\n`);
    }
  }
}

async function renderHuman(action: import("../lib/ontology-gen/types.public").Action, client: string) {
  // Inline the helper logic so we don't need to import (avoids ESM cycle)
  const { renderHumanTaskActionObject } = await import("../lib/ontology-gen/v4/templates/human-task-helper");
  const enriched = { action, dataObjectSchemas: {}, eventSchemas: {} };
  return renderHumanTaskActionObject(enriched, { client });
}

function toKebab(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2").toLowerCase();
}

function toCamelLower(name: string): string {
  return name.replace(/^[A-Z]/, (m) => m.toLowerCase());
}
