#!/usr/bin/env node
/**
 * CLI: propagate the public type contract from `lib/ontology-gen/types.public.ts`
 * to the consumer-facing `generated/action-object.types.ts`. See spec §9.6.
 *
 * Behavior:
 *   1. Read lib/ontology-gen/types.public.ts
 *   2. Prepend a 3-line banner
 *   3. Write to --output (default: generated/action-object.types.ts)
 *
 * No env, no network, no transformation of the type definitions themselves.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE_REL = "../lib/ontology-gen/types.public.ts";
const DEFAULT_OUTPUT = "generated/v3/action-object.types.ts";

interface CliFlags {
  output: string;
  quiet: boolean;
}

main().catch((err: unknown) => {
  process.stderr.write(`gen-action-types failed: ${err instanceof Error ? err.stack ?? err.message : String(err)}\n`);
  process.exit(1);
});

async function main(): Promise<void> {
  const flags = parseArgv(process.argv.slice(2));

  const here = dirname(fileURLToPath(import.meta.url));
  const sourcePath = resolve(here, SOURCE_REL);
  const sourceText = await readFile(sourcePath, "utf8");

  const banner = [
    `// AUTO-GENERATED by scripts/gen-action-types.ts at ${new Date().toISOString()}`,
    `// source: lib/ontology-gen/types.public.ts`,
    `// DO NOT EDIT — regenerate via: npm run gen:ontology:types`,
  ].join("\n");

  const output = `${banner}\n\n${sourceText}`;

  await mkdir(dirname(flags.output), { recursive: true });
  await writeFile(flags.output, output, "utf8");

  if (!flags.quiet) {
    process.stderr.write(`[gen:ontology:types] wrote ${flags.output}\n`);
  }
}

function parseArgv(argv: string[]): CliFlags {
  const flags: CliFlags = { output: DEFAULT_OUTPUT, quiet: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]!;
    switch (arg) {
      case "--output": {
        const v = argv[i + 1];
        if (v === undefined || v.startsWith("--")) usage(`--output expects a path`);
        flags.output = v!;
        i++;
        break;
      }
      case "--quiet":
        flags.quiet = true;
        break;
      case "-h":
      case "--help":
        process.stdout.write(`Usage: npm run gen:ontology:types [-- --output <path>] [--quiet]\n`);
        process.exit(0);
      default:
        usage(`unknown flag: ${arg}`);
    }
  }
  return flags;
}

function usage(msg: string): never {
  process.stderr.write(`error: ${msg}\n`);
  process.exit(2);
}
