// AUTO-GENERATED by scripts/gen-action-snapshot.ts at 1970-01-01T00:00:00.000Z
// source: action=manualEntry id=1-2 domain=RAAS-v1 template=v3
// DO NOT EDIT — regenerate via: npm run gen:ontology -- --action-name manualEntry

import type { ActionObject } from "../../generated/v3/action-object.types";

export const manualEntryActionObject: ActionObject = {
  id: "1-2",
  name: "manualEntry",
  description: "人工需求录入 - 交付经理或招聘专员在RAAS系统中手动创建和录入客户招聘需求信息，包括岗位名称、职级要求、招聘人数、工作城市等核心字段。录入完成后触发需求分析流程。",
  submissionCriteria: "",
  category: "人工操作",
  actor: [
    "Human"
  ],
  trigger: [],
  targetObjects: [
    "Job_Requisition_Specification",
    "Job_Requisition",
    "Client"
  ],
  inputs: [
    {
      "description": "目标客户的唯一编号。用于关联新建的招聘需求至对应客户。",
      "name": "client_id",
      "required": true,
      "sourceObject": "Client.client_id",
      "type": "String"
    },
    {
      "description": "HSM手动填写的岗位信息，包括岗位名称/职责/要求/人数/城市/薪资范围等核心字段。",
      "name": "job_details",
      "required": true,
      "sourceObject": "",
      "type": "JSON"
    }
  ],
  outputs: [
    {
      "description": "新创建的招聘岗位唯一编号。",
      "name": "job_requisition_id",
      "type": "String"
    },
    {
      "description": "新创建的外包招聘需求唯一编号。",
      "name": "job_requisition_specification_id",
      "type": "String"
    }
  ],
  actionSteps: [
    {
      "description": "交付经理或招聘专员在RAAS系统中手动填写客户招聘需求信息，包括岗位名称、职级要求、招聘人数、工作城市、薪资范围、岗位职责、岗位要求等字段，系统创建Job_Requisition_Specification和Job_Requisition记录。",
      "inputs": [
        {
          "description": "目标客户编号。",
          "name": "client_id",
          "sourceObject": "Client.client_id",
          "type": "String"
        },
        {
          "description": "岗位核心信息。",
          "name": "job_details",
          "sourceObject": "",
          "type": "JSON"
        }
      ],
      "name": "手动录入需求",
      "objectType": "action",
      "order": 1,
      "outputs": [
        {
          "description": "创建的招聘岗位编号。",
          "name": "job_requisition_id",
          "type": "String"
        },
        {
          "description": "创建的外包招聘需求编号。",
          "name": "job_requisition_specification_id",
          "type": "String"
        }
      ],
      "rules": []
    }
  ],
  sideEffects: {
    "dataChanges": [
      {
        "action": "CREATE",
        "description": "创建外包招聘需求记录。",
        "objectType": "Job_Requisition_Specification",
        "propertyImpacted": [
          "job_requisition_specification_id",
          "client_id",
          "start_date",
          "deadline",
          "create_time",
          "create_by",
          "status"
        ]
      },
      {
        "action": "CREATE",
        "description": "创建招聘岗位记录并写入HSM手动录入的岗位核心信息。",
        "objectType": "Job_Requisition",
        "propertyImpacted": [
          "job_requisition_id",
          "job_requisition_specification_id",
          "client_job_title",
          "job_responsibility",
          "job_requirement",
          "headcount",
          "city",
          "salary_range",
          "work_years",
          "degree_requirement"
        ]
      }
    ],
    "notifications": []
  },
  triggeredEvents: [
    "REQUIREMENT_LOGGED"
  ],

  prompt: `## Action specification: manualEntry

The block below is the formal specification of the action \`manualEntry\`. It is part of a larger user message; the runtime supplies inputs and additional context separately. Treat this block as a binding contract: do not deviate from the declared steps, do not write outside the declared targets, and do not return outputs outside the declared schema. If preconditions are unmet or required inputs are missing, follow Error policy.

- Category: 人工操作
- Actor:    Human

## Purpose
人工需求录入 - 交付经理或招聘专员在RAAS系统中手动创建和录入客户招聘需求信息，包括岗位名称、职级要求、招聘人数、工作城市等核心字段。录入完成后触发需求分析流程。

## Inputs
The runtime provides these as a JSON object on the inbound payload; field names match exactly. Validate before proceeding; if a required field is missing, follow Error policy.

- client_id (String, required) ← Client.client_id: 目标客户的唯一编号。用于关联新建的招聘需求至对应客户。
- job_details (JSON, required): HSM手动填写的岗位信息，包括岗位名称/职责/要求/人数/城市/薪资范围等核心字段。

## Steps
1. 手动录入需求 [action]
   description:  交付经理或招聘专员在RAAS系统中手动填写客户招聘需求信息，包括岗位名称、职级要求、招聘人数、工作城市、薪资范围、岗位职责、岗位要求等字段，系统创建Job_Requisition_Specification和Job_Requisition记录。
   inputs:
   - client_id (String) ← Client.client_id — 目标客户编号。
   - job_details (JSON) — 岗位核心信息。
   outputs:
   - job_requisition_id (String) — 创建的招聘岗位编号。
   - job_requisition_specification_id (String) — 创建的外包招聘需求编号。

## Output
Return a JSON object matching this schema. The fields below are required; do not include extra keys.

- job_requisition_id (String): 新创建的招聘岗位唯一编号。
- job_requisition_specification_id (String): 新创建的外包招聘需求唯一编号。

\`\`\`json
{
  "job_requisition_id": "<String>",
  "job_requisition_specification_id": "<String>"
}
\`\`\`

## Side-effect boundary

### writes
- Job_Requisition_Specification / CREATE
   fields: job_requisition_specification_id, client_id, start_date, deadline, create_time, create_by, status
   note:   创建外包招聘需求记录。
- Job_Requisition / CREATE
   fields: job_requisition_id, job_requisition_specification_id, client_job_title, job_responsibility, job_requirement, headcount, city, salary_range, work_years, degree_requirement
   note:   创建招聘岗位记录并写入HSM手动录入的岗位核心信息。

### reads
Client

### emits
- REQUIREMENT_LOGGED

Anything outside the above is out of scope; refuse and surface via Error policy.

## Error policy
- Missing or invalid required input → return {"status":"failed","reason":"<which field>","retry":false}; do not partially execute.
- Upstream resource unreachable or auth failure → return {"status":"failed","reason":"<...>","retry":true}.

## Completion criteria
The action is complete when ALL of:

1. Each step has run to its declared termination, or its failure has been surfaced per Error policy.
2. The Output JSON contains all required keys (job_requisition_id, job_requisition_specification_id) and conforms to the schema in Output.
3. Any required outbound event has been emitted (success events on success; alert events on failure).

## Before returning
Verify all of the following before responding:

- Output JSON conforms to the Output schema (no extra or missing keys).
- No write occurred outside Side-effect boundary.
- Every required notification or outbound event has been emitted.`,

  sections: {
    "actionSpec": "## Action specification: manualEntry\n\nThe block below is the formal specification of the action `manualEntry`. It is part of a larger user message; the runtime supplies inputs and additional context separately. Treat this block as a binding contract: do not deviate from the declared steps, do not write outside the declared targets, and do not return outputs outside the declared schema. If preconditions are unmet or required inputs are missing, follow Error policy.\n\n- Category: 人工操作\n- Actor:    Human",
    "beforeReturning": "## Before returning\nVerify all of the following before responding:\n\n- Output JSON conforms to the Output schema (no extra or missing keys).\n- No write occurred outside Side-effect boundary.\n- Every required notification or outbound event has been emitted.",
    "completionCriteria": "## Completion criteria\nThe action is complete when ALL of:\n\n1. Each step has run to its declared termination, or its failure has been surfaced per Error policy.\n2. The Output JSON contains all required keys (job_requisition_id, job_requisition_specification_id) and conforms to the schema in Output.\n3. Any required outbound event has been emitted (success events on success; alert events on failure).",
    "errorPolicy": "## Error policy\n- Missing or invalid required input → return {\"status\":\"failed\",\"reason\":\"<which field>\",\"retry\":false}; do not partially execute.\n- Upstream resource unreachable or auth failure → return {\"status\":\"failed\",\"reason\":\"<...>\",\"retry\":true}.",
    "inputsSpec": "## Inputs\nThe runtime provides these as a JSON object on the inbound payload; field names match exactly. Validate before proceeding; if a required field is missing, follow Error policy.\n\n- client_id (String, required) ← Client.client_id: 目标客户的唯一编号。用于关联新建的招聘需求至对应客户。\n- job_details (JSON, required): HSM手动填写的岗位信息，包括岗位名称/职责/要求/人数/城市/薪资范围等核心字段。",
    "output": "## Output\nReturn a JSON object matching this schema. The fields below are required; do not include extra keys.\n\n- job_requisition_id (String): 新创建的招聘岗位唯一编号。\n- job_requisition_specification_id (String): 新创建的外包招聘需求唯一编号。\n\n```json\n{\n  \"job_requisition_id\": \"<String>\",\n  \"job_requisition_specification_id\": \"<String>\"\n}\n```",
    "preconditions": null,
    "purpose": "## Purpose\n人工需求录入 - 交付经理或招聘专员在RAAS系统中手动创建和录入客户招聘需求信息，包括岗位名称、职级要求、招聘人数、工作城市等核心字段。录入完成后触发需求分析流程。",
    "ruleIndex": null,
    "sideEffectBoundary": "## Side-effect boundary\n\n### writes\n- Job_Requisition_Specification / CREATE\n   fields: job_requisition_specification_id, client_id, start_date, deadline, create_time, create_by, status\n   note:   创建外包招聘需求记录。\n- Job_Requisition / CREATE\n   fields: job_requisition_id, job_requisition_specification_id, client_job_title, job_responsibility, job_requirement, headcount, city, salary_range, work_years, degree_requirement\n   note:   创建招聘岗位记录并写入HSM手动录入的岗位核心信息。\n\n### reads\nClient\n\n### emits\n- REQUIREMENT_LOGGED\n\nAnything outside the above is out of scope; refuse and surface via Error policy.",
    "steps": "## Steps\n1. 手动录入需求 [action]\n   description:  交付经理或招聘专员在RAAS系统中手动填写客户招聘需求信息，包括岗位名称、职级要求、招聘人数、工作城市、薪资范围、岗位职责、岗位要求等字段，系统创建Job_Requisition_Specification和Job_Requisition记录。\n   inputs:\n   - client_id (String) ← Client.client_id — 目标客户编号。\n   - job_details (JSON) — 岗位核心信息。\n   outputs:\n   - job_requisition_id (String) — 创建的招聘岗位编号。\n   - job_requisition_specification_id (String) — 创建的外包招聘需求编号。"
  },

  meta: {
    "actionId": "1-2",
    "actionName": "manualEntry",
    "compiledAt": "1970-01-01T00:00:00.000Z",
    "domain": "RAAS-v1",
    "templateVersion": "v3"
  },
};
